---
title: "Assignment 4"
author:
  - "Ingrid-Liv Morkken"
  - "Thibiga Kuddyar"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
library(tidyverse)
library(lubridate)
library(modelr)
library(broom)
library(lmtest)
library(sandwich)
library(viridis)
})
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

# Modeller

## Leser inn data

```{r}
pm2 <- read_csv("data/pm2.csv", show_col_types = FALSE)
```

```{r}
pm2 <- pm2 %>% 
  mutate(
    fnr = str_sub(knr, 1,2),
    aar_f = str_sub(aar)
  )
```

```{r}
head(pm2)
```




```{r}
pm2 %>% 
  mutate(
    fnr = parse_factor(fnr, levels =fnr),
    aar_f = parse_factor(aar_f, levels = aar_f)
  )
```

```{r}
pm2 <- pm2 %>% 
  mutate(
    Trade_pc_100K = Trade_p/100000
  )
```

```{r}
head(pm2, n = 4)
```

```{r}
mod1 <- 'pm2 ~ aar_f + Total_ya_p + inc_k1 + inc_k5 + uni_k_mf + uni_i_mf + Trade_pc_100K'
```

i.
```{r}
lm1 <- lm(mod1, data = pm2, subset = complete.cases(pm2))
```

```{r}
summary(lm1)
```

ii. 
```{r}
pm2 %>% 
  add_residuals(lm1)
```

# Forklaring

i.
ii.

# Teste for heteroskedastisitet 

i. 
```{r}
bptest(lm1)
```




## Vet ikke om denne er riktig engang lol 
ii. Dersom p-verdien er større enn 0.05 kan vi forkaste H0 og dermed kan har vi heteroskedastisitet. I denne testen har vi ikke heteroskedastisitet. 

```{r}
library(gvlma)
gvlma(lm1)
```

iii.

```{r}
coeftest(lm1)
```

```{r}
vcovHC(lm1)
```


iv.

```{r}
pm2 <- pm2 %>% 
  add_residuals(lm1)
```

v.

```{r}
pm2 <- pm2 %>%
  mutate(aar_d =make_date(aar))
```


vi.

```{r}
pm2 <- pm2 %>%  mutate(fylke = substr(knr, start = 1, stop = 2))

pm2 <- pm2 %>% 
filter(fylke %in% c("01", "02", "03", "11", "12"))
```



vii-x
```{r}
pm2 %>% 
  unnest(c(fylke)) %>% 
  group_by(fylke, aar_d) %>%
  summarise(mean_fylke = mean(resid)) %>% 
  ggplot(mapping = aes(x = aar_d, y= mean_fylke, colour=fylke)) + geom_line(lwd=1)+
  geom_line(lwd=1)+
  geom_hline(yintercept=0, colour = "white")+
  theme(legend.position= "bottom")
```


# Dummy 

i og ii.

```{r}
mod2 <- 'pm2 ~ aar_f*fnr + Total_ya_p + inc_k1 + inc_k5 + uni_k_mf + uni_i_mf + Trade_pc_100K'
lm2 <- lm(mod2, data = pm2)
summary(lm2)
```

iii.

```{r}
pm2 <- pm2 %>% 
  mutate(res_m2 = resid(lm2))
```

iv

```{r}
pm2 %>% filter(fnr %in% c("01", "02", "04", "11", "12")) %>% 
  ggplot(mapping = aes(x= aar_d, y=res_m2))+
  geom_line(aes(group = knavn)) + 
  scale_size_manual(values = c(seq(2.0, 0.5, by = -0.1))) +
  geom_hline(yintercept=0) +
  theme(legend.position='bottom')+
  facet_wrap(~fylke)
```

i., ii.


iii.


```{r}
pm2 %>% filter(knr %in% c("11")) %>% 
  ggplot(mapping=aes(x = aar_d, y = res_m2)) +
  scale_color_viridis(discrete=TRUE, option = "D") +
  geom_line(aes(group = knavn, colour = knavn, size = knavn)) +
  scale_size_manual(values = c(seq(2.0, 0.5, by = -0.1))) +
  geom_hline(yintercept = 0) +
  theme(legend.position='bottom')
```


i


```{r}
pm2 %>% filter(knr %in% c("1119", "1120", "1127", "1121", "1130", "1135", "1106", "1149")) %>% 
  ggplot(mapping=aes(x = aar_d, y = res_m2)) +
  geom_line(aes(group = knavn)) +
  scale_size_manual(values = c(seq(2.0, 0.5, by = -0.1))) +
  geom_hline(yintercept = 0) +
  theme(legend.position="bottom")
```


ii. 

# Modell for hvert år

```{r}
pm2_n <- pm2 %>% 
  group_by(aar)  %>% 
  select(pm2, fnr, knr, aar, aar_f, Menn_ya_p, Kvinner_ya_p,Total_ya_p, inc_k1, inc_k5, uni_k_mf, uni_l_mf, Trade_pc_100k) %>% 
  nest()
```

```{r}
pm2_n
```


```{r}
pm2_n$data [[1]] %>%
  head(n = 5)
```

```{r}
kom_model <- function (a_df) {
  lm(pm2 ~ fnr + Total_ya_p + inc_k1 + inc_k5 + uni_k_mf + uni_l_mf + Trade_pc_100k, data = pm2)
}
```

```{r}
pm2_n <- pm2_n %>% 
  mutate(model = map(data, .f = kom_model))
```

```{r}
kom_model(pm2_n$aar) %>% 
  summary()
```

```{r}
pm2_n %>% 
  filter(aar%in% c("2008")) %>% 
  .$model %>% 
  map_df(glance) %>% 
  print()
```

```{r}
mod_sum <- pm2_n %>% 
  filter(aar %in% c("2008", "2009", "2011", "2012", "2013", "2014", "2015", "2016", "2017")) %>% 
  mutate(mod_summary = map (.x = model, .f = glance)) %>% 
  unnest(mod_summary) %>% 
  print ()
```

```{r}
coef_df <- mod_sum %>% 
  map_df() %>% 
  as.tibble()
```

