---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default 
---

```{r Setup}
suppressPackageStartupMessages({
library(PxWebApiData)
library(tidyverse)
library(lubridate)
})
knitr::opts_chunk$set(echo=FALSE, include=FALSE)
```


```{r}
load("knr.Rdata")
```

```{r}
pm2_raw <- ApiData(
  urlToData = "06035",
  Region = knr,
  ContentsCode = "KvPris",
  Boligtype = "01",
  Tid = c(as.character(2002:2017))
)
```

```{r}
pm2 <- pm2_raw$dataset %>% 
  tibble() %>% 
  select(-Boligtype, -ContentsCode) %>%
  rename(
     knr = Region,
     aar = Tid, 
     pm2 = value
  )
```

```{r}
pm2 <- pm2 %>% 
  select(knr, aar, pm2)
head(pm2)
```


```{r}
names(pm2_raw)[[1]] <- "desc"
```

```{r}
pm2 <- pm2 %>% 
  mutate(
    knavn = pm2_raw$desc$region) %>% 
      group_by(knr) %>% 
      select(knr,aar, pm2, knavn)
```

```{r}
load("test_string_tib.Rdata")
moenster <- '\\s*\\([\\d\\s-]*\\d*\\)\\s*$'
```

```{r}
pm2 <- pm2 %>% 
  mutate(
    knavn = str_replace(knavn, moenster, ""))
```


```{r}
pm2 %>% 
  map_df(is.na) %>% 
  map_df(sum) %>% 
  as.tibble()
```

```{r}
pm2_2006 <- pm2 %>% 
  filter(aar >= 2006) %>% 
  pivot_wider(names_from = aar,
              values_from = pm2)
```

```{r}
pm2_2006 %>% 
  complete.cases() %>% 
  sum
```

```{r}
pm2_2008 <- pm2 %>% 
  filter(aar >= 2008) %>% 
  pivot_wider(names_from = aar,
              values_from = pm2
              )
```

```{r}
pm2_2008 %>% 
  complete.cases() %>% 
  sum
```

```{r}
pm2 <- pm2_2008 %>% 
  na.omit(pm2)
```


```{r}
# time to clean up
rm(pm2_raw, test_string_tib)
```

# Befolkning 

```{r}
pop_08_17_ya_raw <- ApiData(
  urlToData = "07459",
  Region = knr,
  Kjonn = c(1,2),
  Alder =list("agg:TredeltGrupperingB2",
              c("F20-64")),
  Tid = c(as.character(2008:2017))
  )$dataset %>% 
  select(-ContentsCode, -Alder)
```


```{r}
pop_08_17_ya <- pop_08_17_ya_raw %>% 
  pivot_wider(
    id_cols = c(Region, Tid),
    names_prefix= "sex",
    names_from = Kjonn,
    values_from = value)
```


```{r}
names(pop_08_17_ya)[[1]] <- "knr"
names(pop_08_17_ya)[[2]] <- "aar"
names(pop_08_17_ya)[[3]] <- "ya_Menn"
names(pop_08_17_ya)[[4]] <- "ya_Kvinner"
```


```{r}
pop_08_17_ya <- pop_08_17_ya %>% 
  mutate(ya_Total = ya_Menn+ya_Kvinner)
```
 
```{r}
dim(pop_08_17_ya)
```
# TIL OSS: Vi får 4230 når det skulle ha vært 2140. 


```{r}
pop_08_17_raw <- ApiData(
  urlToData = "07459",
  Region = knr,
  Kjonn = c(1,2),
  Alder = list("agg:TodeltGrupperingB",
               c("H17", "H18")),
  Tid =c(as.character(2008:2017))
)$dataset %>% 
  select(-ContentsCode)
```

```{r}
pop_08_17 <- pop_08_17_raw %>% 
  pivot_wider(
    names_from = Kjonn,
    values_from =value)
```


```{r}
names(pop_08_17)[[1]] <- "knr"
names(pop_08_17)[[2]] <- "Alder"
names(pop_08_17)[[3]] <- "aar"
names(pop_08_17)[[4]] <- "Menn"
names(pop_08_17)[[5]] <- "Kvinner"
```

```{r}
pop_08_17 <- pop_08_17 %>% 
  pivot_wider(
    names_from = Alder,
    values_from = c(Menn, Kvinner))
```



```{r}
pop_08_17 <- pop_08_17 %>% 
  mutate(Menn_t = Menn_H17 + Menn_H18) %>% 
  mutate(Kvinner_t = Kvinner_H17 + Kvinner_H18) %>% 
  mutate(Totalt_t = Menn_t + Kvinner_t)
```

```{r}
pop_08_17 <- pop_08_17 %>% 
  select(knr, aar, Menn_t, Kvinner_t, Totalt_t)
```

```{r}
dim(pop_08_17)
```

```{r}
names(pop_08_17)
```

```{r}
pop_08_17_ya_p <- merge(pop_08_17, pop_08_17_ya)
```

```{r}
pop_08_17_ya_p <- pop_08_17_ya_p %>% 
  mutate(Menn_ya_p = ya_Menn/Menn_t*100) %>% 
  mutate(Kvinner_ya_p = ya_Kvinner/Kvinner_t*100) %>% 
  mutate(Total_ya_p = ya_Total/Totalt_t*100)
```


```{r}
pop_08_17_ya_p <- pop_08_17_ya_p %>% 
  select(knr, aar, Menn_ya_p, Kvinner_ya_p, Total_ya_p)
```

```{r}
head(pop_08_17_ya_p, n=5)
```

```{r}
rm(pop_08_17_raw, pop_08_17_ya_raw, pop_08_17, pop_08_17_ya, pm2_2006, pm2_2008)
```

# Intektsdesiler 

```{r}
inc_08_17_raw <- ApiData(
  urlToData = "12558",
  Region = knr,
  Desiler = c("01", "02", "09", "10"),
  ContentsCode = "AndelHush",
  InntektSkatt = "00",
  Tid = c(
    as.character(2008:2017)
  )
)$dataset %>% 
  select(Region, Desiler, Tid, value)
```

```{r}
inc_08_17_raw <- ApiData(
  urlToData="12558",
  Region = knr,
  Desiler = c("01", "02", "09", "10"),
  ContentsCode = "AndelHush",
  InntektSkatt ="00",
  Tid = c(
    as.character(2008:2017)
  )
)$dataset %>% 
  select(Region, Desiler, Tid, value)
```


# Utdanning

```{r}
utdanning_08_17 <- ApiData(
  urlToData = "09429",
  Region = knr,
  Nivaa = c("03a", "04a"),
  Kjonn = c(1,2),
  ContentsCode = "Personer",
  Tid = c(as.character(2008:2017))
  )$dataset %>% 
  select(-ContentsCode, -value)
```

```{r}
inc_08_17 <- inc_08_17_raw %>% 
  pivot_wider(
    names_from = Desiler,
    values_from = value)
```

```{r}
names(inc_08_17)[[1]]<- "knr"
names(inc_08_17)[[2]]<- "aar"
names(inc_08_17)[[3]]<- "Desil_1"
names(inc_08_17)[[4]]<- "Desil_2"
names(inc_08_17)[[5]]<- "Desil_9"
names(inc_08_17)[[6]]<- "Desil_10"
```


```{r}
inc_08_17 <- inc_08_17 %>% 
  mutate(inc_k1 = Desiø_1 + Desil_2) %>% 
  mutate(inc_k5 = Desil_9 + Desil_10)
```

```{r}
inc_08_17 <- inc_08_17 %>% 
  select(knr, aar, inc_k1, inc_k5)
```

```{r}
names(inc_08_17)
```

```{r}
dim(inc_08_17)
```

```{r}
pm2 <- merge(pm2, inc_08_17)
```

```{r}
rm(inc_08_17, inc_08_17_raw, pop_08_17_ya_p)
```


# Handelsomsetning per innbygger - **hvor hører dette til?**

```{r}
trade_08_17 <- ApiData(
  urlToData = "04776",
  Region = knr
```

```{r}
Trade_pc <- 
```

# Prosent av befolkning med universitet/høgskolen utdanning 

```{r}
uni_p_raw <- ApiData(
  urlToData = "09429",
  Region = knr, 
  Nivaa = c("03a", "04a"),
  Kjonn = TRUE,
  ContentsCode = "PersonerProsent",
  Tid = c(
    as.charachter(2008:2017)
    
  )
)
```

```{r}
uni_p_raw <- tibble(
  knr = uni_p_raw$dataset$Region,
  aar = uni_p_raw$dataset$Tid,
  Kjonn = uni_p_raw$`09429: Personer 16 år og over, etter region, nivå, kjønn, statistikkvariabel og år`$kjønn,
  Nivaa = uni_p_raw$`09429: Personer 16 år og over, etter region, nivå, kjønn, statistikkvariabel og år`$nivå,
  uni_p = uni_p_raw$dataset$value
)

head(uni_p_raw, n=5)
```


```{r}
uni_p_raw <- uni_p_raw %>%
  mutate(
    Kjonn = fct_recode(Kjonn, 
                       "mf" = "Begge kjønn",
                       "f" = "Kvinner"
                       "m" = "Menn"
    )
  )
```

```{r}
uni_p_raw <- uni_p_raw %>%
  mutate(
    
  )
```

```{r}
head(uni_p_raw, n = 8)
```


